# Generated by Django 4.0.5 on 2022-07-29 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='contacto_celular',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='contacto_mail',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='date_published',
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='descripcion_docente_a',
        ),
    ]
