# Generated by Django 4.0.6 on 2022-07-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nombre_apellido',
            field=models.CharField(help_text='Colocar su nombre y luego su apellido', max_length=40),
        ),
    ]
