# Generated by Django 4.0.6 on 2022-07-27 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Nombre de Usuario')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electronico')),
                ('nombres', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre/s')),
                ('apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Apellido/s')),
                ('imagen', models.ImageField(upload_to='perfil/', verbose_name='Imagen de Perfil')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='anuncio',
            name='is_headline',
        ),
        migrations.AlterField(
            model_name='anuncio',
            name='descripcion_clase',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='descripcion_docente',
            field=models.CharField(max_length=1000),
        ),
    ]
