# Generated by Django 4.0.6 on 2022-07-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alter_anuncio_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anuncio',
            name='imagen',
            field=models.FilePathField(blank=True, null=True, path='/img'),
        ),
    ]
