# Generated by Django 4.0.5 on 2022-08-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_anuncio_celular_aviso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anuncio',
            name='celular_aviso',
        ),
    ]
